name: CI

on: [push, pull_request]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  test:
    name: Test
    needs: [fmt]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - '1.40.0'
        features:
          - ''
          - gzip
          - hyper
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-registry-${{ matrix.features }}-${{ hashFiles('**/Cargo.*') }}
      - name: Cache Cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-build-target-${{ matrix.features }}-${{ hashFiles('**/Cargo.*') }}
      - name: Build
        if: matrix.features == 'hyper'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --no-default-features --features=${{ matrix.features }}
      - name: Test
        if: matrix.features == 'hyper'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=${{ matrix.features }}
      - name: Check
        if: matrix.features != 'hyper'
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose --no-default-features --features=${{ matrix.features }}
      - name: Check Rustdoc
        if: matrix.features == 'hyper'
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --no-default-features --features=${{ matrix.features }}
